call run_test.bat 5 5 1 1 test_inc_inc c
call run_test.bat 5 5 1 2 test_inc_dec c
call run_test.bat 5 5 1 3 test_inc_rnd c
call run_test.bat 5 5 2 1 test_dec_inc c
call run_test.bat 5 5 2 2 test_dec_dec c
call run_test.bat 5 5 2 3 test_dec_rnd c
call run_test.bat 5 5 3 1 test_rnd_inc c
call run_test.bat 5 5 3 2 test_rnd_dec c
call run_test.bat 5 5 3 3 test_rnd_rnd c